### PR TITLE
Relax roadie dependency to allow v4.x

### PR DESCRIPTION
**Pull request by adzap**
Allow usage with v4.x of roadie gem

### CODE REVIEW

**Comment by Mange** [comment]
I was pretty sure `>=` should allow 4.x here. Are you sure it prevents that version?

**Comment by adzap** [comment]
It was not a ‘>=‘ but a ‘~>’. The ‘~> 3.1’ will only allow >= 3.1.0 to 3.x gem variants.

**Comment by Mange** [comment]
Well I be damned. Thank you!

I wonder about those CI errors. I suppose something needs to be changed in the embedded Rails apps nowadays.
I'll see what I can do about that.

**Comment by adzap** [comment]
Thank you!

Those errors looked too hairy for me to just wander into at the moment.

**Comment by Mange** [comment]
Please rebase on top of `master` to get a working base to work on. You might also want to add an entry to the Changelog.

**Comment by adzap** [comment]
And thank you!

**Comment by Mange** [comment]
Version 2.1.1 was just released with this fix in it.

**Comment by adzap** [comment]
Great thank you!

**Pull request merged**
