### PR TITLE
Test against Ruby 2.3.0 on Travis CI

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by tricknotes** [comment]
Now I'm working on failing tests.

**Comment by tricknotes** [comment]
I think https://github.com/Mange/roadie-rails/pull/52 fixes this failing tests.
When it merged, I'll rebase this PR.

**Comment by Mange** [comment]
Thanks. No need to rebase, just merge `master` after #52 is merged. :smile: 

This is approved; just waiting for the build to pass. :+1:

**Comment by tricknotes** [comment]
Yes, sir! :sunglasses:

**Comment by Mange** [comment]
I added this in #54. Thanks again! :heart:

**Pull request closed without merging**
