### PR TITLE
Adds initial Github Action

### PR DESCRIPTION
**Pull request by davidwessman**
- Since Travis is no longer free.
- Upgrade codecov to non deprecated uploader based on:
  https://docs.codecov.com/docs/deprecated-uploader-migration-guide#ruby-uploader
  
2021-12-19: Tested out on my local branch and it now builds and runs tests for 2.6.9, 2.7.5 and 3.0.3 for all the Rails-versions available. Includes the change in #100 just to be able to run.

### CODE REVIEW

**Comment by davidwessman** [comment]
I am testing this out on:
https://github.com/davidwessman/roadie-rails/pull/1

Not sure what is required to run the actions in this repo.

**Comment by Mange** [comment]
Very nice work here. Thank you for doing this. I was not looking forward to making this migration myself.

All the output looks sane in the PR on your fork. I'll merge this one!

Would you mind fixing all other references to "Travis" in the codebase? Both in README and in `setup.sh`.

**Comment by davidwessman** [comment]
> Very nice work here. Thank you for doing this. I was not looking forward to making this migration myself.
> 
> All the output looks sane in the PR on your fork. I'll merge this one!
> 
> Would you mind fixing all other references to "Travis" in the codebase? Both in README and in `setup.sh`.

🙂 Glad to be able to help!

I updated all the Travis-references I could find, not 100% if I got the status badge right, we will have to iterate when we see it in action. I kept the word `Travis` in two of the comments related to the difference in setup on Travis vs Github Actions.

**Review by Mange — APPROVED** [review]

**Comment by Mange** [comment]
Excellent. Thank you! :heart:

**Pull request merged**
