### PR TITLE
Rails 6 support

### PR DESCRIPTION
**Pull request by jeremy**

### CODE REVIEW

**Comment by Fudoshiki** [comment]
Any plans merge it?

**Comment by Fudoshiki** [comment]
merge?

**Comment by Fudoshiki** [comment]
Hello, what's block this PR?

**Comment by Mange** [comment]
> What's the block

Life. I'll get to it eventually. Feel free to use this fork for the moment.

Is Rails 6 out?

**Comment by Mange** [comment]
So I see that this is for "Rails master". I won't have time to follow Rails master since this gem is [now under passive maintenance](https://github.com/Mange/roadie/issues/155) so I will close this PR.

Please open a new PR when Rails 6 is out (beta or RC is also fine).

I still want to thank you for your time. I am sorry for letting you down. :disappointed:

**Comment by jeremy** [comment]
> I won't have time to follow Rails master since this gem is now under passive maintenance so I will close this PR.

I understand. However, I think this PR will help you with passive maintenance. By tracking the "next" Rails release, Roadie contributors can take over significant maintenance responsibility, guided by CI against their pull requests. Help us help you 😊

**Comment by Mange** [comment]
I don't understand how. You still need to generate a new app on every release or that version isn't tracked, and Rails changes their defaults/configs/code generation occasionally so this generated app could get more and more out of date, giving us less and less confidence over time.

I'm probably just missing something. I cannot reopen since the underlying branch was force pushed, but you could open a new PR and it can be discussed in that PR if you want.

**Comment by jeremy** [comment]
You're absolutely right that it's not maintenance-free! Just a way to help shift some of the responsibility for forward compatibility to PR authors.

**Pull request closed without merging**
