### PR TITLE
Support Rails 7 alpha

### LINKED ISSUE #94: Possible to allow for Rails 7 alpha?
I'd like to use edge rails, which is 7.0.0.alpha. But roadie prevents this with the gem spec:

```
 spec.add_dependency "railties", ">= 5.1", "< 6.2"
```

Any chance of getting that updated?

### PR DESCRIPTION
**Pull request by SeanLF**
closes #94 

Note: rails 7 requires ruby 2.7 minimum, not sure how to modify the test matrix to only test rails 7 with ruby 2.7 and later

## Changes

- adds ruby 3 to the test matrix
- adds support for rails 7 alpha

## Tests

tests pass

### CODE REVIEW

**Comment by Mange** [comment]
This looks excellent. Thank you for taking time to add this! :heart: 

> Note: rails 7 requires ruby 2.7 minimum, not sure how to modify the test matrix to only test rails 7 with ruby 2.7 and later

I have an idea and will experiment a bit with it.

**Comment by Mange** [comment]
I've squashed together your changes into a new commit and opened a new PR with the Travis changes in #97.

**Comment by SeanLF** [comment]
Thanks @Mange!

**Comment by Mange** [comment]
Version 2.3.0 was just pushed with this included.

**Pull request closed without merging**
